FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

# nest cli 포함한 devDependencies 설치
RUN npm install


COPY . .

# Generate Prisma Client
# Generate Prisma Client
RUN npx prisma generate

CMD ["npm", "run", "start:dev"]
